### ISSUE TITLE
Would you consider releasing the pretrained model used in the paper ?

### ISSUE THREAD

**Issue by GabbySuwichaya** [martius-lab/blackbox-deep-graph-matching#1]
Hello, thank you very much for releasing the python scripts, especially the training script which is the most _important_ part. 

I enjoy reading your paper, and your technique is very interesting and the method seems very efficient (~30 images per second that include feature extraction).  

Due to my great interest in this work, I would like to kindly ask if you would consider releasing the pre-trained model that can be used directly to reproduce the results in the paper directly? 

My interest is nothing more than to test the model with my own dataset and application which is different from the usage in the paper.   

Also, it would be great to have some reference after I actually conduct the training process.

**Comment by dominikzietlow** [comment]
As using the models for inference takes you to go through the full setup anyways (so you're just one step away from training), we would ask for your understanding that we do not host snapshots of the pre-trained models.

**Comment by GabbySuwichaya** [comment]
Thank you very much for your support... Actually, it is ok....
