### ISSUE TITLE
How the method scales with the number of keypoints

### ISSUE THREAD

**Issue by GabbySuwichaya** [martius-lab/blackbox-deep-graph-matching#3]
Hi! I would like to ask about how the method scales with the number of keypoints? 
At the moment, I am interested in applying this work to my application. However, the number of keypoints in my problem is much larger  (about 10-100 times) than the PascalVOC dataset. Do you have any recommendations for setting this method to keep the runtime low?

**Comment by dominikzietlow** [comment]
Hey!

You can speed up the matching by restricting the problem to linear costs (e.g. matching only vertices, not the edges).

Cheers,
Dominik

**Comment by GabbySuwichaya** [comment]
@dominikzietlow ... Could you pointing into more details...
I am so sorry I am not really used to this optimization problem... 

Do you mean reducing the problem from quadratic to linear optimization, as follows? It would be nice if you could clarify the approach...  Also, actually, I have run it... but the accuracy becomes all 0 (I checked this by running the voc_unfiltered.json) !!! 

Does this mean that I should train the new model for this case?  

**From** (something like this)
```
matchings = [
                    gm_solver(unary_costs, quadratic_costs)
                    for gm_solver, unary_costs, quadratic_costs in zip(gm_solvers, unary_costs_list, quadratic_costs_list)
                ]
```
 
**To this**

```
matchings = [
                    gm_solver(unary_costs, [])
                    for gm_solver, unary_costs in zip(gm_solvers, unary_costs_list)
                ]
```

**Comment by dominikzietlow** [comment]
You would definitely need to train from scratch. And to be sure not just remove the costs, but remove the edges from the matching completely.

**Comment by GabbySuwichaya** [comment]
@dominikzietlow. Thanks so much. I will try again and if there is anything I will come back here for your kind help.
